CREATE TABLE [dbo].[Clients]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Name] NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Clients_Id PRIMARY KEY (Id),
	CONSTRAINT UC_Clients_Name UNIQUE ([Name])
)
